#!/bin/sh
### BEGIN INIT INFO
# Provides:          umountfs
# Required-Start:
# Required-Stop:
# Default-Start:
# Default-Stop:      0 6
# Short-Description: Turn off swap and unmount all local file systems.
# Description:
### END INIT INFO

PATH=/sbin:/bin:/usr/sbin:/usr/bin

mountAndSetCookie() {
    echo "Remounted /foxtmp for reboot-cookie"
    mount /foxtmp
    mkdir -p /foxtmp/etc
    echo "$1" > /foxtmp/etc/reboot-cookie
}

echo "Deactivating swap..."
swapoff -a

# We leave /proc mounted.
echo "Unmounting local filesystems..."
grep -q /mnt/ram /proc/mounts && mount -o remount,ro /mnt/ram
sync
mount -o remount,ro /
echo "Remounted / as RO..."
sync
# leave /foxusr mounted, umount it in reboot
rcookie=$(cat /foxtmp/etc/reboot-cookie)
umount -f -a -r > /dev/null 2>&1
if [[ $rcookie = 1 ]]; then
    mountAndSetCookie "$rcookie"
elif [[ $rcookie = 2 ]]; then
    mountAndSetCookie "$rcookie"
fi
mount -t sysfs none /sys
echo "Running ubidetach commands..."
ubidetach -d 1
umount /sys -f

: exit 0
